src/Entity/Pin.php
<?php

namespace App\Entity;

use App\Entity\Traits\Timestampable;
use App\Repository\PinRepository;
use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=PinRepository::class)
 * @ORM\Table(name="pins")
 * * @Vich\Uploadable
 * @ORM\HasLifecycleCallbacks
 */
class Pin
{
    use Timestampable;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="le titre ne peut pas être vide")
     * @Assert\Length(min=3)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="la description ne peut pas être vide")
     * @Assert\Length(min=10)
     */
    private $description;

        /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="pin_image", fileNameProperty="imageName")
     * @Assert\Image(maxSize="8M", maxSizeMessage="Le fichier est trop grand ({{ size }}{{ suffix }}). Taille maximale autorisée {{ limit }} {{ suffix }}")
     * 
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageName;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="pins")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

        /**
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->setUpdatedAt(new \DateTimeImmutable);
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }


}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use App\Entity\Traits\Timestampable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="users")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(fields={"email"}, message="Il semblerait que vous ayez déja un compte !")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    use Timestampable;
    
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank(message="merci de saisir votre adresse mail")
     * @aSSERT\Email(message="Merci de saisir une adresse mail valide")
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Merci de saisir votre prénom")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Merci de saisir votre nom")
     */
    private $lastName;

    /**
     * @ORM\OneToMany(targetEntity=Pin::class, mappedBy="user", orphanRemoval=true)
     */
    private $pins;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    public function __construct()
    {
        $this->pins = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * @return Collection<int, Pin>
     */
    public function getPins(): Collection
    {
        return $this->pins;
    }

    public function addPin(Pin $pin): self
    {
        if (!$this->pins->contains($pin)) {
            $this->pins[] = $pin;
            $pin->setUser($this);
        }

        return $this;
    }

    public function removePin(Pin $pin): self
    {
        if ($this->pins->removeElement($pin)) {
            // set the owning side to null (unless already changed)
            if ($pin->getUser() === $this) {
                $pin->setUser(null);
            }
        }

        return $this;
    }

    public function getFullName(): string 
    {
        return $this -> getFirstName() . ' ' . $this -> getLastName();
    }

    public function getGravatarUrl(int $size = 200)
    {
        return 'https://www.gravatar.com/avatar/'. md5(strtolower(trim($this->getEmail()))) .'/?s='.$size;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
}

src/Form/PinType.php
<?php

namespace App\Form;

use App\Entity\Pin;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class PinType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('imageFile', VichImageType::class, [
                'label' => 'Image (fichier JPG ou PNG)',
                'required' => false,
                'allow_delete' => true,
                'delete_label' => 'supprimer',
                'download_uri' => false,
                'image_uri' => true,
                'imagine_pattern' => 'squared_thumbnail_small'
            ])
            ->add('title', TextType::class, [
                'label' => 'Titre'
            ])
            ->add('description', TextareaType::class, [
                'label' => 'Description'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Pin::class,
        ]);
    }
}

src/Controller/PinsController.php
<?php

namespace App\Controller;
use App\Entity\Pin;
use App\Form\PinType;
use App\Repository\PinRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;


class PinsController extends AbstractController
{
    /**
     * @Route("/", name="app_home", methods="GET")
     */
    public function index(PinRepository $pinRepository): Response
    {
        $pins = $pinRepository->findBy([], ['createdAt' => 'DESC']);


        return $this->render('pins/index.html.twig', compact('pins'));
    }

    /**
     * @Route("/pins/create", name="app_pins_create", methods="GET|POST")
     * @Security("is_granted('ROLE_USER') && user.isVerified() == true")
     */
    public function create(Request $request, EntityManagerInterface $em, UserRepository $userRepo ): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');

        $pin = new  Pin;
        $form = $this->createForm(PinType::class, $pin);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $pin -> setUser($this->getUser());
            $em -> persist($pin);
            $em -> flush();

            $this->addFlash('success', 'Le pin à été créé avec succés !');

            return $this->redirectToRoute('app_home');

        }
        
        return $this->render('pins/create.html.twig', ['form'=> $form->createView()]);
    }

    /**
     * @Route("/pins/{id<[0-9]+>}", name="app_pins_show", methods="GET")
     */
    public function show(Pin $pin): Response
    {
        return $this->render('pins/show.html.twig', compact('pin'));
    }

    /**
     * @Route("/pins/{id<[0-9]+>}/edit", name="app_pins_edit", methods={"GET", "PUT", "POST"})
     * @IsGranted("PIN_MANAGER", subject="pin")
     */
    public function edit(Request $request, Pin $pin, EntityManagerInterface $em): Response
    {
        $form = $this->createForm(PinType::class, $pin);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em -> flush();

            $this->addFlash('info', 'Le pin à été édité avec succés');

            return $this->redirectToRoute('app_home');

        }

        return $this->render('pins/edit.html.twig', [
            'pin' => $pin,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/pins/{id<[0-9]+>}/delete", name="app_pins_delete", methods={"DELETE|POST"})
     * @IsGranted("PIN_MANAGER", subject="pin")
     */
    public function delete(Request $request, Pin $pin, EntityManagerInterface $em): Response
    {
        if ($this->isCsrfTokenValid('pin_deletion_' . $pin->getId(), $request->request->get('csrf_token'))) {
            $em->remove($pin);
            $em->flush();

            $this->addFlash('error', 'Le pin à été effacé avec succés');
        }
       return $this->redirectToRoute('app_home');
    }
}

templates/pins/_form.html.twig
    {{form_start(form)}}
        {{form_widget(form)}}
        <div class="d-grid gap-2">
            <input class="btn btn-primary" type="submit" value="{{submitButtonText}}" formnovalidate>
        </div>
    {{form_end(form)}}

templates/pins/create.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title "New pins" %}

{% block body %}
<div class="row">
    <div class="col-md-6 mx-auto">
        <h1>Create Pin</h1>
        {{ include('pins/_form.html.twig', {submitButtonText: 'Create Pin'})}}
    </div>
</div>
{% endblock %}

templates/pins/edit.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title 'edit pin #' ~ pin.id %}

{% block body %}
<div class="row">
    <div class="col-md-6 mx-auto">
        <h1>edit Pin {{pin.title}}</h1>
        {{include('pins/_form.html.twig', {'submitButtonText': 'Update Pin'})}}
    </div>
</div>
{% endblock %}

templates/pins/index.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title %}find all the best pins on earth !{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>
                                {# {{dump(app.user)}} #}

    {% if pins|length > 0 %}
        <h1 class="text-center text-muted mb-4">{{pluralize(pins|length, 'Pin')}}</h1>
        {% for row in pins|batch(3) %}
            <div class="row mb-5">
                {% for pin in row %}
                    <div class="col-md-4">
                        <article class="pin bg-white rounded shadow">
                            <div class="mw-100 rounded-top overflow-hidden">
                                <a href="{{path('app_pins_show', {id: pin.id})}}">
                                    <img src="{{ (pin.imageName ? vich_uploader_asset(pin) : asset('build/images/unavailable.webp')) | 
                                    imagine_filter('squared_thumbnail_medium')}}" alt="{{pin.title}}" class="w-100">
                                </a>
                            </div>
                            <h2 class="h5 p-3"><a href="{{path('app_pins_show', {id: pin.id})}}" class="text-secondary text-decoration-none">{{pin.title}}</a></h2>
                            <p class="text-muted p-3"><small>Submitted by {{pin.user.fullName}}</small></p>
                            {# <a href="#" class="btn btn-danger m-3" onclick="event.preventDefault(); confirm('Etes vous sur ?') && document.getElementById('js-pin-delete-form-{{ pin.id }}').submit();">&times; Supprimer</a>
                            <form id="js-pin-delete-form-{{ pin.id }}" action="{{path('app_pins_delete', {id: pin.id})}}" method="post" style="display: none;">
                                <input type="hidden" name="csrf_token" value="{{csrf_token('pin_deletion_' ~ pin.id)}}">
                                <input type="hidden" name="_method" value="DELETE">
                            </form> #}
                        </article>
                    </div>    
                {% endfor %}
            </div>
        {% endfor %}
    {% else %}
        <p class="h1 mt-5 text-center">Pas encore de pin crée ! <a href="{{path('app_pins_create')}}">Soyez le premier !</a></p>
    {% endif %}    
{% endblock %}

templates/pins/show.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title pin.title %}

{% block body %}
    <div class="d-flex justify-content-between mb-5">
        <a href="{{ path('app_home') }}"><button class="btn btn-warning btn-lg shadow">Retour à l'accueil</button></a>
    </div>
    <h1 class="text-center text-muted mb-3">{{ pin.title }}</h1>
    <div class="row">
        <div class="col-md-6 mx-auto">
            <article class="pin bg-light rounded shadow-lg">
                <div class="mw-100 rounded-top overflow-hidden align-items-center justify-content-center d-flex">
                    <img src="{{ (pin.imageName ? vich_uploader_asset(pin) : asset('build/images/unavailable.webp')) | 
                    imagine_filter('squared_thumbnail_medium')}}" alt="{{pin.title}}" class="w-75">
                </div>
                <div class="p-3">
                    <h1 class="h5 text-secondary text-decoration-none">{{pin.title}}</h1>
                    <p class="text-muted">
                        <small>
                            Submitted 
                                <time datetime="{{pin.createdAt|date('Y-m-d H:i:s')}}">{{pin.createdAt|ago}}</time>  
                            by {{pin.user.fullName}}
                        </small>
                    </p>
                    <p class="text-break">
                    {{pin.description}}
                    </p>
                    {% if is_granted('PIN_MANAGER', pin) %}
                    <div class="py-3">
                        <a href="{{path('app_pins_edit', {id: pin.id}) }}" class="btn btn-info">Edit</a>
                        <a href="#" onclick="event.preventDefault(); confirm('Etes vous sur ?') && document.getElementById('js-pin-delete-form').submit();" class="btn btn-danger">Delete</a>
                        <form id="js-pin-delete-form" action="{{path('app_pins_delete', {id: pin.id})}}" method="post" style="display: none;">
                            <input type="hidden" name="csrf_token" value="{{csrf_token('pin_deletion_' ~ pin.id)}}">
                            <input type="hidden" name="_method" value="DELETE">
                        </form>
                    </div>
                    {% endif %}
                </div>
            </article>
        </div>
    </div>
{% endblock %}